### ISSUE TITLE
urllib

### ISSUE THREAD

**Issue by AndreV84** [samwize/python-email-crawler#13]
could you advise please on
a) how to resolve: python email_crawler.py "iphone developers"
  File "email_crawler.py", line 96
    except urllib2.URLError, e:
                           ^
SyntaxError: invalid syntax
b) how to crawl emails from a specific country, e.g all emails from .it or .com

Thanks

**Comment by Axlo** [comment]
I'm having the same problem with line 96. Whats the solution?

Thanks

**Comment by tiagoamx** [comment]
@AndreV84 @Axlo  I noticed this error when using python 3, but with python 2.7.9 it's ok

**Comment by AndreV84** [comment]
Is there a way to use the crawler to gather email addresses from a
top-level domain like .com or .it or whatever?
Are you aware of implementations of that approach?
How do one scan a top level domain ?
Please advise.

**Comment by ArthurCockfield** [comment]
@AndreV84 you need to change all except urllib2.URLError, e: to except urllib2.URLError as e:

**Comment by AndreV84** [comment]
Thank you for the update!
I am just wondering if I could search for specific domain email addresses, like *.com or * it.
Thanks

**Comment by ArthurCockfield** [comment]
@AndreV84  Haven't been able to get it to run. Have you? It seems like the reason it's not working is because the syntax is different for python 3x. Also missing libraries

**Comment by AndreV84** [comment]
I did just run it and it seems running:
[11:47:12] INFO::email_crawler - Crawling https://www.wired.com/tag/hacks/
Is there a way to search for all emails which belong to a specific domain?

**Comment by ArthurCockfield** [comment]
@andreV84 what version of python are you running? And how did you fix the issue with URLparse if you're using python 3 and greater.

**Comment by ArthurCockfield** [comment]
@AndreV84 for all emails hunter.io is software which keeps a database of specific domains

**Comment by AndreV84** [comment]
thank you for letting me know!

**Comment by AndreV84** [comment]
I think I am using python 2.7

**Comment by ArthurCockfield** [comment]
@AndreV84 Okay thanks for letting me know. Is the output supposed to be "logging.config.dictconfig<logging> after the program is running? Does that mean it is doing the searches?
